### ISSUE TITLE
BRobot could not be found

### ISSUE THREAD

**Issue by bendnorman** [RobotExMachina/Machina.NET#2]
Hello!

I am trying to build `EXAMPLE_ConnectionCheck` however I receive the error:

`The type or namespace name 'BRobot' could not be found (are you missing a using directive or an assembly reference?)`

Any suggestions?

Thanks

**Comment by nonoesp** [comment]
Hi @bendnorman!

`Machina` was formerly called `BRobot` and it seems these sample projects haven't been updated.

You might give a try to build `Machina` and change `using BRobot` for `using Machina` in `ConnectionCheck.cs`.

**Comment by garciadelcastillo** [comment]
@nonoesp is right, these samples should be updated to the new Machina namespace.
