### ISSUE TITLE
Online programming in KUKA

### ISSUE THREAD

**Issue by atelier-soma** [RobotExMachina/Machina.NET#20]
Is there any development regarding online programming with KUKAs.
Would it be possible to use WorkVisual (Kukas version of ABBs RobotStudio)?

**Comment by Arastookhajehee** [comment]
Hi @atelier-soma,

Well as far as I am familiar, WorkVisual is used for programming and deploying programs onto the robot. Basically, you would alter programs as a part of a "Project" and then you would "Deploy" that project onto the robot's hard drive. There is no real-time programming of KRL files in WorkVisual based on my understanding. 
online programming of KUKA robots is actually a work in progress and we're actively working on it. Presumably, Coming Soon! :D

Also, KUKA does not have a fully-fledged program like RobotStudio. The equivalent in KUKA is called KUKA.Sim. However, KUKA.Sim is very limited compared to what you would get from RobotStudio. it does not have a virtual plex-pendant, as an example. If you want that there is another program called Office.Lite. Simply speaking, it's a whole different world it seems.

Cheers!

**Comment by garciadelcastillo** [comment]
And when @Arastookhajehee says `we`, he means `he` is working super actively right now in implementing an early prototype of this for Machina :) More updates soon! 💪

**Comment by garciadelcastillo** [comment]
Hey @atelier-soma , see #21 :)
