### ISSUE TITLE
RoboDk Extruder function

### ISSUE THREAD

**Issue by filipemribeir** [RobotExMachina/Machina.NET#4]
Hello! 
I'm working on a 3D printing project at University of Coimbra and I'm using RoboDK and python. However I'm facing a problem with a Extruder Call during my simulation because I don't know how to build it and I have no idea how it works, because I'm new at all this kinds of things and I'm working on my own. 
If you could give me some guides or tips I would appreciate with because I'm stuck in this problem. 
best Regards from Portugal 
Filipe Ribeiro

**Comment by garciadelcastillo** [comment]
Hi Filipe, 

Thanks for reaching out. RoboDK is a fantastic product for robot simulation, and we are working to make Machina fully compatible with its API. Unfortunately, we can't provide support for it. I suggest you contact Albert Nubiola and his team, they are fantastic people and can probably give you better support than we do ;)

If you are interested in generating robot programs offline for 3D printing, I suggest you take a look at the Machina implementations for Grasshopper and/or Dynamo: 
https://github.com/RobotExMachina/Machina-Grasshopper
https://github.com/RobotExMachina/Machina-Dynamo

You can then simulate the generated programs in RoboDK ;)


JL
