### ISSUE TITLE
Machina could not be found

### ISSUE THREAD

**Issue by Godsgrav3** [RobotExMachina/Machina.NET#8]
Hi,

I made a new solution in Robotstudio with a controller selected from a layout. when try to build `ConnectionCheck.cs`. I get this the following error: 
`ConnectionCheck.cs(18,7): error CS0246: The type or namespace name 'Machina' could not be found (are you missing a using directive or an assembly reference?)`

Does anyone know how to solve this?

thanks

**Comment by garciadelcastillo** [comment]
Hi @wsvdyk 

Looks like you are trying to build `EXAMPLE_ConnectionCheck`, and the core project `Machina` is not properly referenced? Try going to Refences on that project, and making sure you link the Machina assembly to the cloned project (I might be using some local path that is not available on your system).

Let me know if you got this.

**Comment by Godsgrav3** [comment]
hi @garciadelcastillo 

I think I found my issue, both .net and the bridge still had there *-master name from GitHub. I renamed those 2 folders and now I can run `EXAMPLE_ConnectionCheck` from `machina` without a problem.

Thank you for your quick reply.

Wesley
