### ISSUE TITLE
want to creating new action

### ISSUE THREAD

**Issue by Godsgrav3** [RobotExMachina/Machina.NET#9]
Hi,

I have been using Machina for a little while now and I want to implement a new action. I have done several things to do this. I'm now at sending the new action to Robotstudio and I do not know what I'm doing wrong.

The action that I want to implement is prod1(). it has no parameters and doesn't need any.

in `ABBCommunicationProtocol` I have added a new case:
```
case ActionType.Prod1:
    msgs.Add(string.Format(CultureInfo.InvariantCulture,
    "{0}{1} {2}",
    STR_MESSAGE_ID_CHAR,
    action.Id,
    INST_CUSTOM_PROD1,
    STR_MESSAGE_END_CHAR));
    break;
```
When I use this action it will not be sent to Robotstudio. When I do another action (MoveTo), both prod1() and MoveTo(300,300,400) will show up in Robotstudio, see image for information.[image (prnt.sc)](https://prnt.sc/ne5e6n)

But when I update the case to this:
```
case ActionType.Prod1:
    msgs.Add(string.Format(CultureInfo.InvariantCulture,
    "{0}{1} {2} {3}",  //added {3}
    STR_MESSAGE_ID_CHAR,
    action.Id,
    INST_CUSTOM_PROD1,
    STR_MESSAGE_END_CHAR));
    break;
```
When I send this this action is send to robotstudio I get `corrupt parameter` error in robotstudio this is not shocking and I expect it to do so when it is send like this.

When I update the case one more time to this:
```
case ActionType.Prod1:
    msgs.Add(string.Format(CultureInfo.InvariantCulture,
    "{0}{1} {2} {3}",  //added {3}
    STR_MESSAGE_ID_CHAR,
    action.Id,
    INST_CUSTOM_PROD1,
    300,  //added 300 parameter
    STR_MESSAGE_END_CHAR));
    break;
```
I get the same issue as before that prod() and moveTo(300,300,400) are sent together to Robotstudio.

So I do not know why and how Machina is sending these 2 actions together to Robotstudio, but it will send one with 'corrupt parameter' but not one with the 'good parameters'.

If you need more information please let know, I will add what I can.

any help is highly appreciated,

Wesley

**Comment by garciadelcastillo** [comment]
Hi @wsvdyk,

It's a little hard to tell what the problem might be without looking at the full code. Do you have a fork/c
commit to look at?

My guesses here are:
- In your first attempt you were missing the end char, and therefore was joining it to the second action.
- In your second attempt, you have a whit space between the instruction type code and the message end char. The parser on RobotStudio side expects more parameters, and that's why you get the corrupt error. It should probably be this:
```
case ActionType.Prod1:
    msgs.Add(string.Format(CultureInfo.InvariantCulture,
    "{0}{1} {2}{3}",  //added {3}, make sure there is no white space before STR_MESSAGE_END_CHAR
    STR_MESSAGE_ID_CHAR,
    action.Id,
    INST_CUSTOM_PROD1,
    STR_MESSAGE_END_CHAR));
    break;
```

I believe this corrected second option should work, let me know if that's the case. 

Happy to see you are hacking the tool and expanding it, would be curious to see what are you applying this to ;)

**Comment by Godsgrav3** [comment]
Hi @garciadelcastillo,

I can give you a big hug at the moment! It was indeed the white space between `{2}` and `{3}`.

To answer you on what I'm applying it to. I'm currently doing an internship at a company and they gave us a project to control ABB robots (and others in the [far] future) from a database with instructions.

I will upload the code to my fork when I have the time to remove a lot of things that are not useful anymore, like writeline and useless comments :)

I do have one more question and that is about machinabridge. I have very limited knowledge about c# so it might be very simple. In `MainWindow_handlers.cs` there are variables that I find in the GUI (MainWindow.xml) but those variables are not known in `MainWindow_handlers.cs`. A short list of variables I refer to are: 'InputBlock`, `btn_Connect`, `txtbox_Ip` and `txtbox_Port`. 

EDIT: for some reason, `InputBlock`, `btn_Connect`, `txtbox_Ip` and `txtbox_Port` are known on my PC with exactly the same code but not known on my laptop(which I use most often). I assume this is an issue with my laptop, you can ignore my question above.

**Comment by garciadelcastillo** [comment]
Happy we found the fix :)

I am not sure about the variables issue. If it is working differently in different clones, maybe the projects is are not properly linked on your laptop, and the namespaces not found?

**Comment by garciadelcastillo** [comment]
> To answer you on what I'm applying it to. I'm currently doing an internship at a company and they gave us a project to control ABB robots (and others in the [far] future) from a database with instructions. I will upload the code to my fork when I have the time to remove a lot of things that are not useful anymore, like writeline and useless comments :)

If you produce some kind of visual outcome of your project, lmk and Ill be happy to add it to the [project colletion](https://www.youtube.com/playlist?list=PLvxxYImPCApXZ-yBCUtGzVWb2ZhduaSXR) :)

**Comment by Godsgrav3** [comment]
> Happy we found the fix :)
> 
> I am not sure about the variables issue. If it is working differently in different clones, maybe the projects is are not properly linked on your laptop, and the namespaces not found?

The link should be the same, as the code from my laptop is uploaded to my computer. It might be that visual link was not installed with c# in mind. 

I will keep the project collection in mind.
